ImmichFrame.Desktop/app.manifest, ImmichFrame/App.axaml.cs, ImmichFrame/Helpers/AssetHelper.cs, ImmichFrame/Helpers/HttpClientExtensionMethods.cs, ImmichFrame/ImmichFrame.csproj, ImmichFrame/Models/AssetInfo.cs, ImmichFrame/Models/Settings.cs, ImmichFrame/Settings.example.xml, ImmichFrame/ViewModels/MainViewModel.cs, ImmichFrame/Views/MainView.axaml.cs, README.md
- Code and solution cleanup (move classes into separate files, renamings, etc.)
- Add ability to add album IDs to Settings.xml to use albums as datasource
Fixes #9
@3rob3 I had to add the Settings.xml to the solution again, not sure if you meant to fully remove it. I had problems with my debug folder not having a Settings.xml. Hope this is OK, feel free to make more changes.
=> Ability to choose multiple albums as datasource

ImmichFrame/Exceptions/ImmichFrameExceptions.cs, ImmichFrame/Helpers/AssetHelper.cs, ImmichFrame/Models/AssetInfo.cs, ImmichFrame/Models/Settings.cs, ImmichFrame/Settings.example.xml, ImmichFrame/ViewModels/MainViewModel.cs, ImmichFrame/Views/MainView.axaml, ImmichFrame/Views/MainView.axaml.cs, README.md
=> Ability to display memories

ImmichFrame/Helpers/AssetHelper.cs, ImmichFrame/ImmichFrame.csproj, ImmichFrame/Models/AssetResponseDto.cs, ImmichFrame/Models/ImmichApi.cs, ImmichFrame/Models/Settings.cs, ImmichFrame/OpenAPIs/immich-openapi-specs.json, ImmichFrame/Views/MainView.axaml.cs
Use OpenApi to generate client, display ExifInfo Desc if no ImageDesc was set
=> OpenApi, Imagedesc

.gitignore, ImmichFrame/Views/MainView.axaml.cs
Moved Settings.CurrentSettings inside Try/Catch of Onloaded. If file was missing there was no message to user.
Also added entry to .gitignore for ".mono/"
=> Move-Setting.CurrentSettings-to-OnLoaded

ImmichFrame/Settings.example.xml, ImmichFrame/ViewModels/MainViewModel.cs, ImmichFrame/ViewModels/MainWindowViewModel.cs, ImmichFrame/ViewModels/ViewModelBase.cs, ImmichFrame/Views/BaseView.cs, ImmichFrame/Views/MainView.axaml, ImmichFrame/Views/MainView.axaml.cs
MainView Cleanup -> Logic in ViewModel, Dispose old view when navigating
=> Refactor MainView

ImmichFrame/Views/MainView.axaml
=> Keyboard navigation

ImmichFrame/Views/MainView.axaml, ImmichFrame/Views/SettingsView.axaml
Change SettingsView Int fields to NumericUpDown
=> Change SettingsView Int fields to NumericUpDown

ImmichFrame/App.config, ImmichFrame/Models/Settings.cs, ImmichFrame/Properties/Settings.Designer.cs, ImmichFrame/Properties/Settings.settings, ImmichFrame/Settings.example.xml, ImmichFrame/ViewModels/MainViewModel.cs, ImmichFrame/ViewModels/MainWindowViewModel.cs, ImmichFrame/ViewModels/SettingsViewModel.cs, ImmichFrame/Views/MainView.axaml, ImmichFrame/Views/SettingsView.axaml, ImmichFrame/Views/WindowView.axaml
Added Margin setting
Added NumericUpDown margins to align with other controls (unclear why this needs explicitly set, stackpanel should have done this)
Closes #74
=> Margin setting

ImmichFrame.Android/ImmichFrame.Android.csproj, ImmichFrame/App.axaml, ImmichFrame/App.config, ImmichFrame/Helpers/AssetHelper.cs, ImmichFrame/Models/Settings.cs, ImmichFrame/Properties/Settings.Designer.cs, ImmichFrame/Properties/Settings.settings, ImmichFrame/Settings.example.xml, ImmichFrame/ViewModels/MainViewModel.cs, ImmichFrame/Views/MainView.axaml.cs, ImmichFrame/Views/SettingsView.axaml
=> Create an album for recent ImmichFrame displayed photos

ImmichFrame/Helpers/AssetHelper.cs, ImmichFrame/Models/AssetResponseDto.cs, ImmichFrame/Models/Settings.cs, ImmichFrame/OpenAPIs/immich-openapi-specs.json
Use the new API introduced in v1.106.1
=> API Changes version 1.106.1

ImmichFrame.Android/MainActivity.cs, ImmichFrame.Android/Properties/AndroidManifest.xml, ImmichFrame.Android/ScreenSaverService.cs, ImmichFrame/ViewModels/MainViewModel.cs
=> Add retry to next/prev image closes #88

README.md
This info should probably also be in the Config GUI.
=> Add note about UID from URL to README.md

ImmichFrame/Models/Settings.cs, ImmichFrame/ViewModels/MainViewModel.cs, ImmichFrame/ViewModels/SettingsViewModel.cs, ImmichFrame/Views/MainView.axaml, ImmichFrame/Views/SettingsView.axaml
=> Add image stretch options Closes #103

ImmichFrame/Models/Settings.cs, ImmichFrame/ViewModels/ErrorViewModel.cs, ImmichFrame/ViewModels/MainWindowViewModel.cs, ImmichFrame/ViewModels/WelcomeViewModel.cs, ImmichFrame/Views/WelcomeView.axaml, ImmichFrame/Views/WelcomeView.axaml.cs
=> Welcome page

README.md
Hi. Feel free to modify, but these steps are tested and working. I struggled to get it set up by just searching the web. This works and might help others. Thanks for your great work!
=> Added Raspberry Pi OS autostart instructions

immichFrame.Web/src/lib/components/elements/icon.svelte, immichFrame.Web/src/lib/components/elements/image-component.svelte, immichFrame.Web/src/lib/components/elements/image.svelte, immichFrame.Web/src/lib/components/elements/overlay-controls.svelte, immichFrame.Web/src/lib/components/home-page/home-page.svelte
When no movement or click, this hides:
- Mouse
- Overlay
this also fixes the overlay size (icons)
=> Feat: Hide UI, Mouse & overlay-size fix

.github/workflows/build-docker.yml, Dockerfile, ImmichFrame.WebApi/Program.cs, Makefile
Weather was not showing because the .net runtime 8.0-alpine does not support globalisation. fixed that.
=> Fix: Weather not showing up

ImmichFrame.Core/Logic/ImmichFrameLogic.cs, immichFrame.Web/src/lib/components/elements/asset-info.svelte, immichFrame.Web/src/lib/components/elements/image.svelte
Zoom in or out of (known) faces when available, also show faces in metadata.
This ignores faces that do not have a name (unassigned faces)
=> Feat: Zoom in / out of faces

ImmichFrame.Core/Helpers/CalendarExtensionMethods.cs, ImmichFrame.Core/ImmichFrame.Core.csproj, ImmichFrame.Core/Interfaces/IAppointment.cs, ImmichFrame.Core/Interfaces/IImmichFrameLogic.cs, ImmichFrame.Core/Interfaces/IServerSettings.cs, ImmichFrame.Core/Logic/ImmichFrameLogic.cs, ImmichFrame.Core/Models/Appointment.cs, ImmichFrame.WebApi/Controllers/CalendarController.cs, ImmichFrame.WebApi/Helpers/SettingsExtensonMethods.cs, ImmichFrame.WebApi/Models/ServerSettings.cs, ImmichFrame/Models/Settings.cs, ImmichFrame/Settings.example.json, README.md, docker/example.env, immichFrame.Web/src/lib/components/elements/appointments.svelte, immichFrame.Web/src/lib/components/home-page/home-page.svelte, immichFrame.Web/src/lib/immichFrameApi.ts
=> Feat: Display calendar

immichFrame.Web/src/lib/components/elements/overlay-controls.svelte
- Right arrow -> Next
- Left arrow -> Back (not implemented)
- Space -> Pause/Play
=> Feat: Shortcuts

ImmichFrame.Core/Interfaces/IImmichFrameLogic.cs, ImmichFrame.Core/Logic/ImmichFrameLogic.cs, ImmichFrame.WebApi/Controllers/AssetController.cs, immichFrame.Web/src/lib/components/elements/LoadingElement.svelte, immichFrame.Web/src/lib/components/elements/image-component.svelte, immichFrame.Web/src/lib/components/elements/image.svelte, immichFrame.Web/src/lib/components/home-page/home-page.svelte, immichFrame.Web/src/lib/immichFrameApi.ts
TODO: Metadata-fix for splitview
=> Feat: Splitview for vertical images

immichFrame.Web/src/lib/components/elements/image-component.svelte, immichFrame.Web/src/lib/components/elements/image.svelte
This fixes the splitscreen width on large screens
=> Fix: Splitscreen width

ImmichFrame.Core/Logic/ImmichFrameLogic.cs, immichFrame.Web/src/lib/components/elements/error-element.svelte, immichFrame.Web/src/lib/components/home-page/home-page.svelte
Fixes #163 
Show memories in correct order if only memories are set up.
=> Feat: Show memories in order

immichFrame.Web/package-lock.json, immichFrame.Web/package.json, immichFrame.Web/src/lib/components/elements/image-component.svelte
=> Feat: Happy Birthday🎉

ImmichFrame.Core/Interfaces/IClientSettings.cs, ImmichFrame.WebApi/Models/WebClientSettings.cs, immichFrame.Web/src/app.css, immichFrame.Web/src/lib/components/home-page/home-page.svelte, immichFrame.Web/src/lib/stores/config.store.ts, immichFrame.Web/tailwind.config.js
- Use user defined primary color
- Fallback to default if none is defined
=> Feat: Reimplement Fontcolor-Setting

immichFrame.Web/src/lib/components/elements/overlay-controls.svelte, immichFrame.Web/src/lib/components/home-page/home-page.svelte
Display back button & handle backlog/history
=> Feat: Navigate back

immichFrame.Web/package-lock.json, immichFrame.Web/package.json
Reverts immichFrame/ImmichFrame#212
=> Revert "Bump the npm_and_yarn group across 1 directory with 3 updates"

immichFrame.Web/src/app.css, immichFrame.Web/src/lib/components/elements/asset-info.svelte, immichFrame.Web/src/lib/components/elements/clock.svelte, immichFrame.Web/tailwind.config.js
Addresses suggestion made in request #198 
PR rebased on main replacing #227
Thanks to @iCanHazSkillz
=> Add text-shadow to app.css to improve readability

immichFrame.Web/src/app.html
=> iOS PWA support

immichFrame.Web/src/lib/components/elements/appointments.svelte
Add invoke to GetAppointments and change interval to 10 minutes. Closes #256
=> Calendar fix

ImmichFrame.Core/Interfaces/IServerSettings.cs, ImmichFrame.WebApi/Controllers/AssetController.cs, ImmichFrame.WebApi/Controllers/CalendarController.cs, ImmichFrame.WebApi/Controllers/ConfigController.cs, ImmichFrame.WebApi/Controllers/WeatherController.cs, ImmichFrame.WebApi/Helpers/CustomAuthenticationMiddleware.cs, ImmichFrame.WebApi/Helpers/ImmichFrameAuthenticationHandler.cs, ImmichFrame.WebApi/Models/ServerSettings.cs, ImmichFrame.WebApi/Program.cs, Install_Web.md, README.md, docker/Settings.example.json, docker/example.env, immichFrame.Web/src/lib/components/elements/appointments.svelte, immichFrame.Web/src/lib/components/elements/clock.svelte, immichFrame.Web/src/lib/components/elements/error-element.svelte, immichFrame.Web/src/lib/components/elements/image-component.svelte, immichFrame.Web/src/lib/components/home-page/home-page.svelte, immichFrame.Web/src/lib/immichFrameApi.ts, immichFrame.Web/src/lib/index.ts, immichFrame.Web/src/lib/stores/persist.store.ts
=> Feat: Add authentication via basic secret

ImmichFrame.Core/ImmichFrame.Core.csproj, ImmichFrame.Core/Logic/ImmichFrameLogic.cs, ImmichFrame.Core/OpenAPIs/immich-openapi-specs.json
Reverts immichFrame/ImmichFrame#260
=> Revert "Fix: Immich Api Changes"

ImmichFrame.WebApi/Controllers/AssetController.cs
=> handle quotes for PhotoDateFormat in API

immichFrame.Web/src/lib/components/elements/clock.svelte
Same issue as found with GetAppointments in #257
=> Add invoke to GetWeather timer, simplify time interval

immichFrame.Web/src/lib/components/elements/appointments.svelte
=> Feat: Multiday handling for calendar appointments

ImmichFrame.Core/Logic/ImmichFrameLogic.cs
Caches weather information on the server to avoid unnecessary hits to  OpenWeatherMap API
=> Feat: Cache weather information.

ImmichFrame.WebApi/Program.cs
=> Feat: ASCII-Art

docs/docs/contribute/Setup.md, docs/docs/contribute/_category_.json, docs/docs/demo.md, docs/docs/getting-started/_category_.json, docs/docs/getting-started/apps.md, docs/docs/getting-started/configuration.md, docs/docs/getting-started/installation/_category_.json, docs/docs/getting-started/installation/docker.md, docs/docs/getting-started/installation/prerequisites.md, docs/docs/getting-started/setup.md, docs/docs/overview.md, docs/docusaurus.config.ts
=> doc: Basic documentation Page

ImmichFrame.Core/Api/ImmichApi.cs, ImmichFrame.Core/Helpers/ApiCache.cs, ImmichFrame.Core/Helpers/ImmichFrameExtensionMethods.cs, ImmichFrame.Core/Helpers/WebhookHelper.cs, ImmichFrame.Core/Interfaces/IAppointmentService.cs, ImmichFrame.Core/Interfaces/IImmichFrameLogic.cs, ImmichFrame.Core/Interfaces/IWeatherService.cs, ImmichFrame.Core/Logic/ImmichFrameLogic.cs, ImmichFrame.Core/Logic/OptimizedImmichFrameLogic.cs, ImmichFrame.Core/Services/IcalCalendarService.cs, ImmichFrame.Core/Services/OpenWeatherMapService.cs, ImmichFrame.WebApi/Controllers/AssetController.cs, ImmichFrame.WebApi/Controllers/CalendarController.cs, ImmichFrame.WebApi/Controllers/ConfigController.cs, ImmichFrame.WebApi/Controllers/WeatherController.cs, ImmichFrame.WebApi/Program.cs, immichFrame.Web/src/lib/immichFrameApi.ts
- Decouple Weather Logic
- Decouple Calendar Logic
- New Implementation of the ImmichFrame backend
- Add Cache class
- Sanitize user identifier in log/webhook
=> Feat: Rework Backend, decouple

immichFrame.Web/src/lib/components/elements/clock.svelte
Use sveltekit in rune mode, instead of #346 
Closes #345
=> Fix: Clock update

immichFrame.Web/src/lib/components/elements/asset-info.svelte, immichFrame.Web/src/lib/components/elements/image-component.svelte, immichFrame.Web/src/lib/components/elements/image.svelte, immichFrame.Web/src/lib/components/home-page/home-page.svelte
- Simplify zoom effect & apply zoom effect on debug overlay (cc @ArchyInf)
- Cleanup css & js
- Add icons for assetinfo
~TODO:~
~- work on qr-stuff (#242)~
~- #164~
~- work on #341 maybe?~
~- #183 (maybe)~
EDIT: Will work on the TODOs in another PR to keep them small for @3rob3 😋
=> Feat: Image Rework

immichFrame.Web/src/lib/components/elements/appointments.svelte
Fixes the appointment end time
=> Fix: Appointment end time

ImmichFrame.Core/Logic/OptimizedImmichFrameLogic.cs
OptimizedImmichFrameLogic has an optimisation which loads a queue of assets that can be pulled from to 'GetNextAsset'. There were a few of problems in the code:
* The initial call would always return null, because the queue would be empty -> now it async reloads just as before, but also waits (up to 1min) to the fetch to happen to return an asset (and only returns null if it takes < 1min)
* The code used a standard Queue which is not thread-safe (so could have failed with concurrent modifications) -> replaced with a thread-safe Channel
* The code attempted to prevent concurrent fetches (wait for an existing to complete rather than start a 2nd), but guarded via reading an instance-level bool (where writes may not be observed immediately by another thread) -> replaced with a SlimSemaphore
=> Chore: Cleanup fire-and-forget asset loading

ImmichFrame.WebApi/Program.cs
Switch to implicit DI instance creation
=> Refactor: Use interface implementations in DI

immichFrame.Web/src/lib/components/elements/image-component.svelte, immichFrame.Web/src/lib/components/elements/image.svelte, immichFrame.Web/src/lib/components/home-page/home-page.svelte
Closes #319
- Landscape split mode 
- Small optimization with image fill is set (no need for blurry image in background)
*Maybe a more precise setting is needed, what split modes should be allowed (Layout-Setting)*
=> Feat: Landscape split mode

docs/package-lock.json, docs/package.json
=> Chore: Update docusaurus to newest version

ImmichFrame.Core/Interfaces/IServerSettings.cs, ImmichFrame.WebApi.Tests/Resources/TestV1.json, ImmichFrame.WebApi.Tests/Resources/TestV2.json, ImmichFrame.WebApi/Helpers/Config/ServerSettingsV1.cs, ImmichFrame.WebApi/Models/ServerSettings.cs, Install_Web.md, docker/Settings.example.json, docker/example.env, docs/docs/getting-started/configuration.md, immichFrame.Web/src/lib/components/home-page/home-page.svelte, immichFrame.Web/src/lib/immichFrameApi.ts
=> Feat: Progressbar setting

ImmichFrame.WebApi.Tests/Helpers/Config/ConfigLoaderTest.cs, ImmichFrame.WebApi.Tests/ImmichFrame.WebApi.Tests.csproj, ImmichFrame.WebApi.Tests/Resources/TestV2_NoGeneral.json, ImmichFrame.WebApi/Models/ServerSettings.cs
Specifically allows an empty General section in config
=> Fix: allow empty general settings

CONTRIBUTING.md
There were a few steps missing from the contribution guide that I had to figure out. Updating the file to help the next developer who wants to contribute.
=> Add additional required steps to contribution guide
