- ImmichFrame/Models/Settings.cs
- ImmichFrame/Settings.example.xml
- ImmichFrame/Views/MainView.axaml
- ImmichFrame/Views/MainView.axaml.cs
Closes #42
I could not get data binding to work for the CrossFade Duration so did it in Onloaded. 
Removed "if(_appsettings == null)" because it will be caught now in Settings.cs parse/validate.
> configurable transition duration. Closes Feature requests #42

- ImmichFrame/Helpers/AssetHelper.cs
- ImmichFrame/Models/AssetResponseDto.cs
- ImmichFrame/ViewModels/MainViewModel.cs
Some images (mostly live photos/generated videos) do not have thumbnails. ImmichFrame displays thumbnails. This handles this and skips the asset.
Fixes #53
> Handle assets without a thumbnail / thumb hash

- ImmichFrame/Helpers/ImageHelper.cs
- ImmichFrame/Models/Settings.cs
Generated Regex: https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators
From https://learn.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#decimal-digit-character-d
> \d matches any decimal digit. It is equivalent to the \p{Nd} regular expression pattern, which includes the standard decimal digits 0-9 as well as the decimal digits of a number of other character sets.
> Convert to Generated Regex, remove \d usage

- ImmichFrame/ImmichFrame.csproj
The update to this package from 1382fdbd8e91185a7f01fe6b7fd26b73eebf2cd8 was causing an issue with URLs not being assembled correctly.
> Reverting version of Microsoft.Extensions.ApiDescription.Client and NSwag.ApiDescription.Client packages.

- ImmichFrame/Models/Settings.cs
- ImmichFrame/ViewModels/MainViewModel.cs
I'm making some of my family digital photo frames and need them to be as hands-off as possible since most of them are not very tech-savy.
This mode allows me to silently handle issues such as the Immich server going down (which causes an exception on 404s) and other spurious exceptions without having to get a call from them :)
Figured this will probably be helpful for others as well.
> feat: Adding UnattendedMode setting to enable auto-continue on ErrorView.

- ImmichFrame/Helpers/LocationHelper.cs
- ImmichFrame/Models/Settings.cs
- ImmichFrame/ViewModels/MainViewModel.cs
- ImmichFrame/Views/SettingsView.axaml
Adding State to location display and abbreviating State & Country displays (state only applies to USA & CAN states currently).
The existing display of <City, Country> was ambiguous to me (we Americans love reusing City names in every state :) ), so this change aims to allow including State while also allowing State and Country to be abbreviated to ISO 3166 values.
@JW-CH would love your input on this to make sure I'm not coming at this with too much of a USA/Canada focus. I've only added State-abbreviation logic for those two countries and my understanding is that the only EU state that has "states" is Germany, and I believe all of the other EU states will simply not show any field for "State" as was the case before (and Germany will display a non-abbreviated state currently).
@3rob3 I'm …
> State display & ISO 3166 Abbreviations

- ImmichFrame.Android/ImmichFrame.Android.csproj
- ImmichFrame.Android/MainActivity.cs
- ImmichFrame.Desktop/ImmichFrame.Desktop.csproj
- ImmichFrame/ImmichFrame.csproj
- ImmichFrame/ViewModels/MainWindowViewModel.cs
- ImmichFrame/ViewModels/SettingsViewModel.cs
- ImmichFrame/Views/ErrorView.axaml.cs
- ImmichFrame/Views/SettingsView.axaml
This is a minimal implementation to just show settings screen (instead of error message/exception) if settings.json is not found. The Welcome Page PR will more fully implement this, but I just wanted to add it now in case there is a release before Welcome Page is done. Most of the code was lifted straight from your draft PR for WelcomePage :), so it should be straightforward to merge once that is ready.
Other changes were updating Avalonia, and removing unused Usings.
Closes #104
> Show settings page instead of error message when settings not found.

- ImmichFrame/Helpers/AssetHelper.cs
- ImmichFrame/Helpers/LocationHelper.cs
- ImmichFrame/Helpers/WeatherHelper.cs
- ImmichFrame/Models/AssetResponseDto.cs
- ImmichFrame/Models/Settings.cs
- ImmichFrame/ViewModels/SettingsViewModel.cs
Don't create new instances of Settings everywhere, just directly use Setting.CurrentSettings (with the exception of ViewModels where the properties need to be observable).
> Directly use Settings.CurrentSettings

- ImmichFrame.Core/ImmichFrame.Core.csproj
- ImmichFrame.Core/Logic/ImmichFrameLogic.cs
- ImmichFrame.Core/OpenAPIs/immich-openapi-specs.json
- ImmichFrame.WebApi/Controllers/AssetController.cs
- ImmichFrame.WebApi/Program.cs
> [!WARNING]
This will only work with immich-server version 1.116 or higher
Following things were changed:
- updated Openapi-Specs
- use new random endpoint
- use caching for random endpoint to reduce load on immich api
- use search metadata endpoint instead of deprecated `GetPersonAssets`
- updated generation of immich client
> Use search endpoint for random assets & cache optimizations

- ImmichFrame.WebApi/Controllers/AssetController.cs
- ImmichFrame.WebApi/Controllers/CalendarController.cs
- ImmichFrame.WebApi/Controllers/ConfigController.cs
- ImmichFrame.WebApi/Controllers/WeatherController.cs
- ImmichFrame.WebApi/Models/ImageRequestedNotification.cs
- ImmichFrame.WebApi/Program.cs
- immichFrame.Web/src/lib/components/elements/appointments.svelte
- immichFrame.Web/src/lib/components/elements/clock.svelte
- immichFrame.Web/src/lib/components/elements/image-component.svelte
- immichFrame.Web/src/lib/components/home-page/home-page.svelte
- immichFrame.Web/src/lib/immichFrameApi.ts
- immichFrame.Web/src/lib/stores/identifier.store.ts
- immichFrame.Web/src/routes/+page.ts
Clients are now identified by a random identifier (UUID) that can be overwritten with `?client=MyClient`. This will be persisted and does only need to be called once.
The webhook message will now also show the identifier send by the client. e.g.
```json
{
"Name": "ImageRequestedNotification",
"ClientIdentifier": "Frame_Kitchen",
"DateTime": "2024-12-11T17:40:58.5034185\u002B01:00",
"RequestedImageId": "eee299ac-b9e0-4249-aff9-d0a970e1572c"
}
```
Closes #230
> Feat: Identify client requests

- ImmichFrame.Core/OpenAPIs/immich-openapi-specs.json
- immichFrame.Web/src/lib/immichFrameApi.ts
This fixes the API schema error in #279 by adding the new enum value added in the recent update.
> Add the 'manual' option to the sourceType enum

- docs/index.html
- immichFrame.Web/src/lib/components/elements/image-component.svelte
- immichFrame.Web/src/lib/components/elements/image.svelte
- immichFrame.Web/src/lib/components/home-page/home-page.svelte
On mobile devices with a dynamic viewport size ("URL bar" can be shown/hidden), `h-screen` sets an element's height to the maximum possible viewport size.  This results in the top or bottom of the application being obscured by the URL bar.  
`h-dvh` instead uses the `dvh`  unit to set the element height to the current actual viewport height.  `dvh` is supported in all browsers, most since late 2022, except IE 11.
Only tested in Firefox and Chromium on Linux, Firefox and Chrome on Android, and Safari on iOS, as I am not set up to build and test the native clients.
> Fix: Height on mobile devices by switching from h-screen to h-dvh

- immichFrame.Web/src/lib/components/elements/image.svelte
The image zoom effect "jumps" at the end of its animation back to its un-transformed state.  Normally the slideshow will have moved on before this happens, due to the 2s extra animation length, but if it is paused or the next image takes a particularly long time to load the jump will be visible to the user.
This PR adds a forwards animation fill to all the image zoom animations which should fix the issue.  (The pure `zoom-out` is currently unaffected since `scale(1)` is an identity transform, but I think it's probably good to put the fill in now in case of future changes to the animation.)
> Fix: Add animation fill on image zoom

- ImmichFrame.WebApi/Controllers/AssetController.cs
- immichFrame.Web/src/lib/components/elements/image-component.svelte
- immichFrame.Web/src/lib/components/home-page/home-page.svelte
- immichFrame.Web/src/lib/stores/slideshow.store.ts
Manually paging through images currently feels somewhat sluggish due to a combination of transition time (which is of course desirable for non-manual transitions) and long image load times when connected to a remote api server.
This PR includes two proposed changes in order to improve responsiveness:
* set transition duration to zero when the user manually requests the previous or next image (and then set it back to the configured value at the next automatic transition)
* set cache-control headers to store images in the browser cache for up to one week
I'd be happy to rework these if another approach would be preferable, please let me know.
There's one thing which I did _not_ attempt to implement, but which I think could be quite beneficial: pre-loading the next/"on-deck" image.  I didn't …
> Improve responsiveness when user manually requests prev/next image

- ImmichFrame.WebApi/Controllers/ConfigController.cs
- ImmichFrame.WebApi/ImmichFrame.WebApi.csproj
- ImmichFrame.WebApi/Program.cs
There is currently no way to see backend version number. This will add it to log and also expose an endpoint that can be checked via a client if ever required.
> Add version, version logging, and version endpoint

- ImmichFrame.WebApi/Controllers/AssetController.cs
- immichFrame.Web/src/lib/components/elements/image-component.svelte
- immichFrame.Web/src/lib/components/home-page/home-page.svelte
- immichFrame.Web/src/lib/stores/slideshow.store.ts
Okay, this might need some additional work but I want to get your feedback on the approach (I've reimplemented it a couple of times, this is the best I could find).
This PR would:
* move image loading to home-page
* create a dictionary of loadImage promises, which is updated when the slideshow advances
* load data into imagesState by awaiting those promises
* set cache headers to store images for one week (this is currently relied upon for loading previous images, but we could keep those in JS as well with this approach if we wanted to)
Some things I'm not sure about:
* PRELOAD_IMAGES (the distance ahead in the backlog to fetch) could be configurable?  If it was it should probably also be capped so people don't set it to some huge number.
* It might be worthwhile to construct some kind of …
> Feat: Pre-fetch and cache images

- immichFrame.Web/src/lib/components/elements/clock.svelte
Added shadow to the weather data display which was missing.
Applied `text-shadow-sm` class to the clockweatherinfo element,
matching the styling used in date display and weather description.
Fixes #322
> fix: Add text shadow to weather data display

- immichFrame.Web/src/lib/components/home-page/home-page.svelte
immich does not return people data when using the filtering for albums. This change (pre)fetches this data. This will result in e.g. people being displayed if you have an album filter active.
> Feat: Fetch asset metadata for images without people

- ImmichFrame.Core/Api/AssetResponseDto.cs
- ImmichFrame.Core/Logic/ImmichFrameLogic.cs
- ImmichFrame.Core/Logic/OptimizedImmichFrameLogic.cs
Closes #329
This is just to fix how it used to work. I don't really like how the description gets overwritten by 'x years ago'.
> Fix: Description for memory assets (x years ago)

- immichFrame.Web/src/lib/components/elements/image-component.svelte
logo moving causes the flicker. This seems to fix it for me.
Closes #335
> Fix: Logo flickering

- ImmichFrame.Core/Interfaces/IClientSettings.cs
- ImmichFrame.WebApi/Models/WebClientSettings.cs
- immichFrame.Web/package.json
- immichFrame.Web/src/lib/components/elements/asset-info.svelte
- immichFrame.Web/src/lib/components/elements/image-component.svelte
- immichFrame.Web/src/lib/components/elements/image.svelte
- immichFrame.Web/src/lib/components/elements/imageoverlay/image-overlay.svelte
- immichFrame.Web/src/lib/components/elements/imageoverlay/overlay-item.svelte
- immichFrame.Web/src/lib/components/elements/imageoverlay/overlay-qr.svelte
- immichFrame.Web/src/lib/components/elements/overlay-controls.svelte
- immichFrame.Web/src/lib/components/home-page/home-page.svelte
- immichFrame.Web/src/lib/immichFrameApi.ts
- Basic implementation of a 'more details'/'info' page
- QR-Code takes the base URL from the existing `ImmichServerUrl`
- Image overlay hides the action overlay (<, | |, >)
- Can be closed via the 'x' top right
- Shortcut 'i' to open/close the info overlay
To-do: Implement in client? (Shortcut and for android TV remotes) (cc @3rob3 )
Closes #242
> Feat: Display more details

- .github/workflows/test.yml
Just runs the unit tests. They currently only test loading config versions, but more can be added over time.
> Maintenance: Add GitHub workflow to run tests

- ImmichFrame.WebApi/Controllers/ConfigController.cs
- ImmichFrame.WebApi/Models/ClientSettingsDto.cs
Implemented ClientSettingsDto to provide subset of general settings to clients. Using a DTO means that further evolution of internal model won't change API. Note that `ImmichServerUrl` is omitted as there may now be multiple (and we previously confirmed that it was not used).
> Added ClientSettingsDto to expose subset of general settings in API

- ImmichFrame.Core.Tests/Logic/Pool/AlbumAssetsPoolTests.cs
- ImmichFrame.Core.Tests/Logic/Pool/AllAssetsPoolTests.cs
- ImmichFrame.Core.Tests/Logic/Pool/CachingApiAssetsPoolTests.cs
- ImmichFrame.Core.Tests/Logic/Pool/FavoriteAssetsPoolTests.cs
- ImmichFrame.Core.Tests/Logic/Pool/MemoryAssetsPoolTests.cs
- ImmichFrame.Core.Tests/Logic/Pool/PersonAssetsPoolTests.cs
- ImmichFrame.Core/Helpers/ApiCache.cs
- ImmichFrame.Core/Interfaces/IApiCache.cs
- ImmichFrame.Core/Logic/Pool/AlbumAssetsPool.cs
- ImmichFrame.Core/Logic/Pool/AllAssetsPool.cs
- ImmichFrame.Core/Logic/Pool/CachingApiAssetsPool.cs
- ImmichFrame.Core/Logic/Pool/FavoriteAssetsPool.cs
- ImmichFrame.Core/Logic/Pool/MemoryAssetsPool.cs
- ImmichFrame.Core/Logic/Pool/PeopleAssetsPool.cs
- ImmichFrame.Core/Logic/PooledImmichFrameLogic.cs
- ImmichFrame.Core/Services/IcalCalendarService.cs
- ImmichFrame.Core/Services/OpenWeatherMapService.cs
Switched out the IDictionary cache implementation to an IMemoryCache. 
This allows for proper expiration; the previous one relied on attempting to retrieve an entry to trigger expiration. This one will expire and remove entries asynchronously. It's also a Microsoft class so less code for us to maintain.
(We could probably remove the ApiCache entirely and just use IMemoryCache directly, however the former uses per-cache expiration settings, whereas the latter is per-entry, so is not a drop-in replacement.)
> Chore: Switched to IMemoryCache to correctly handle expiration

- ImmichFrame.Core/Api/AssetResponseDto.cs
- ImmichFrame.Core/Interfaces/IImmichFrameLogic.cs
- ImmichFrame.Core/Logic/AccountSelection/BloomFilterAssetAccountTracker.cs
- ImmichFrame.Core/Logic/AccountSelection/IAssetAccountTracker.cs
- ImmichFrame.Core/Logic/AccountSelection/TotalAccountImagesSelectionStrategy.cs
- ImmichFrame.Core/Logic/MultiImmichFrameLogicDelegate.cs
- ImmichFrame.Core/Logic/PooledImmichFrameLogic.cs
- ImmichFrame.WebApi/Program.cs
- immichFrame.Web/src/lib/components/elements/imageoverlay/image-overlay.svelte
- immichFrame.Web/src/lib/immichFrameApi.ts
This is an alternative fix for https://github.com/immichFrame/ImmichFrame/pull/416
It works a little differently; the ImmichServerUrl is appended to the DTO by the class that is selecting across accounts, rather than the source pool. This allows future pool implementations not to care about the Url as it's appended later.
> Added ImmichServerUrl to AssetResponseDto

- ImmichFrame.Core/Logic/PooledImmichFrameLogic.cs
Allow RefreshAlbumPeopleInterval to be set to zero, which will set the cache timeout to 1ms (it cannot be set to TimeSpan.Zero).
> Permit RefreshAlbumPeopleInterval of 0

- ImmichFrame.Core/ImmichFrame.Core.csproj
- ImmichFrame.Core/Logic/PooledImmichFrameLogic.cs
- ImmichFrame.WebApi.Tests/Controllers/AssetControllerTests.cs
- ImmichFrame.WebApi.Tests/ImmichFrame.WebApi.Tests.csproj
- ImmichFrame.WebApi.Tests/Mocks/MockHttpMessageHandler.cs
- ImmichFrame.WebApi/Controllers/AssetController.cs
- ImmichFrame.WebApi/Program.cs
This performs a test calling through to a mock immich API. Provides a fast sanity test to ensure that data is being passed through the system plus a base to add more service-level testing if we need it.
> Feat: Add AssetController test with direct settings DI

- ImmichFrame.Core.Tests/Logic/Pool/MemoryAssetsPoolTests.cs
- ImmichFrame.Core/Helpers/ApiCache.cs
- ImmichFrame.Core/Logic/Pool/MemoryAssetsPool.cs
- ImmichFrame.Core/Logic/PooledImmichFrameLogic.cs
I noticed that the API caching is set to the same for all types of asset, however it should be fixed to one day for memories as they should be refreshed daily.
> Fix: Memories cache should last one day
